﻿@startuml
skin rose
title Параллельное выполнение АСО
start
  :Инициализация параметров;
  while (Есть ещё итерации?) is (да)
    :Запуск потоков для поиска решений;
    note right: Возможно N-потоков 
    fork 
      :Поиск решения;
      :Обновление локального феромона;
  
      if (Локальное значение > глобального значения?) then (да) 
        :Обновление лучшего значения;
        note left: Разделяемый ресурс
        :Обновление лучшего набора рюкзака;
        note left: Разделяемый ресурс
      else (нет)
      endif
    fork again
      :Поиск решения;
      :Обновление локального феромона;
      if (Локальное значение > глобального значения?) then (да) 
        :Обновление лучшего значения;
        :Обновление лучшего набора рюкзака;
      else (нет)
      endif
    end fork
    :Обновление глобального феромона;
    :Переход к следующей итерации;
  endwhile (нет)
end
@enduml